### ISSUE TITLE
Empty `repeat` loop unintuitively causes stack overflow

### ISSUE THREAD

**Issue by philnguyen** [leanprover/lean4#7925]
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [x] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [x] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [x] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

An empty loop written using the imperative-looking `repeat` construct causes a stack overflow.

### Context

From this [discussion](https://leanprover.zulipchat.com/#narrow/channel/270676-lean4/topic/Tail-call.20optimization.20when.20specializing.20monad.3F/with/511599001) on Zulip.

### Steps to Reproduce

```lean
def main : IO Unit := do repeat pure ()
```

**Expected behavior:** Program keeps running in constant stack space.

**Actual behavior:** Program fails with error
> Stack overflow detected. Aborting.

### Versions

Lean `4.18` and `4.20.0-nightly-2025-04-10`, Mac OS 15.3.2.

**Comment by philnguyen** [comment]
#6172 also has an example of this program during `elab`, but not an exact duplicate, because in that context, it's reasonable to bound the execution. Here it's during the run time of a regular program.

**Comment by zwarich** [comment]
This is almost fixed in the new code generator, but the `boxing` pass removes the loop entirely, resulting in execution of unreachable code:
```
[Compiler.IR] [borrow]
    def Lean.Loop.forIn.loop._at_.main.spec_0 (x_1 : obj) (x_2 : @& obj) : obj :=
      let x_3 : obj := ctor_0[PUnit.unit];
      let x_4 : obj := Lean.Loop.forIn.loop._at_.main.spec_0 x_3 x_2;
      ret x_4
    def main (x_1 : obj) : obj :=
      let x_2 : obj := ctor_0[PUnit.unit];
      let x_3 : obj := Lean.Loop.forIn.loop._at_.main.spec_0 x_2 x_1;
      ⊥
[Compiler.IR] [boxing]
    def Lean.Loop.forIn.loop._at_.main.spec_0 (x_1 : obj) (x_2 : @& obj) : obj :=
      let x_3 : obj := ctor_0[PUnit.unit];
      let x_4 : obj := Lean.Loop.forIn.loop._at_.main.spec_0 x_3 x_2;
      ret x_4
    def main (x_1 : obj) : obj :=
      ⊥
    def Lean.Loop.forIn.loop._at_.main.spec_0._boxed (x_1 : obj) (x_2 : obj) : obj :=
      let x_3 : obj := Lean.Loop.forIn.loop._at_.main.spec_0 x_1 x_2;
      ret x_3
```

**Comment by philnguyen** [comment]
Thanks @zwarich so much for looking into the issue! But from your description, it looks like this is addressing #7923 (reaching `⊥`), as opposed to this one (causing stackoverflow)?

**Comment by zwarich** [comment]
Yes, @digama0, that's correct, except for the last bit. This issue in the old compiler is caused by optimizations introducing new mutual tail recursion:
```
def Lean.Loop.forIn.loop._at.main._spec_1._rarg (x_1 : obj) : obj :=
  let x_2 : obj := ctor_0[PUnit.unit];
  let x_3 : obj := Lean.Loop.forIn.loop._at.main._spec_1 x_2;
  let x_4 : obj := app x_3 x_1;
  ret x_4
def Lean.Loop.forIn.loop._at.main._spec_1 (x_1 : @& obj) : obj :=
  let x_2 : obj := pap Lean.Loop.forIn.loop._at.main._spec_1._rarg;
  ret x_2
```
This does not get compiled to a loop in either compiler. However, the new compiler doesn't introduce this mutual tail recursion, so it would execute as a loop if this other issue with overeager optimization in the face of unreachable code were fixed.

This question of the optimizer introducing mutual tail recursion is maybe more fundamental than this exact issue, and I have some ideas for how to greatly improve it, if not completely fix it.

**Comment by digama0** [comment]
I don't think the lean compiler supports mutual tail recursion? Or maybe there is a middle end pass that thinks it does but the backend doesn't and that's why it's stack overflowing. In the generated C code there is only one function and one `goto _start` available to jump to, so it's impossible to compile mutual tail recursion unless you did more things like introducing a block variable to switch on right after the main loop.

**Comment by zwarich** [comment]
Yes, we don't support optimized mutual tail recursion; I was just referring to the introduction of mutual recursion in tail position where there was plain tail recursion before. The passes that create new decls (specialization, lambda lifting, arity reduction, etc.) can trigger situations like this. Debugging these issues in the new compiler has been a huge part of the time spent making it work on `master`.

We should switch to representing tail recursion explicitly by allowing join points to be recursive. This would immediately unlock some new optimizations (e.g. loop-invariant code motion, inlining functions with loops). It would also open the door to implementation strategies for optimized mutual tail recursion (although neither introducing a switch or duplicating code are perfect).

**Comment by digama0** [comment]
> It would also open the door to implementation strategies for optimized mutual tail recursion (although neither introducing a switch or duplicating code are perfect).

Note that while using a switch is definitely suboptimal code, it may be close enough that LLVM will reliably recognize it and do jump threading to produce the actual code we want in this situation.

**Comment by philnguyen** [comment]
Update: In Lean 4.21, we still get the original problem:
```
Stack overflow detected. Aborting.
```

But with Lean 4.22, we get a different problem:
```
INTERNAL PANIC: unreachable code has been reached
```

**Comment by philnguyen** [comment]
I can no longer reproduce this problem in 4.29, so I'm closing this one. Thank you so much for your great work!
